config/routes.rb
Interviews::Application.routes.draw do
  root :to => "home#index"
  
  resources :panels
  resources :interviewer_pools
  resources :interviewers
  resources :auth

  get "home/index"

end

app/models/panel.rb
require 'valid_email'

class Panel < ActiveRecord::Base
  validates :candidate, :presence => true
  validates :email,     :presence => true, :email => true
  validates :position,  :presence => true
  validates :date,      :presence => true

  has_many :sessions
end

app/controllers/panels_controller.rb
require 'auth_controller'
require 'tzinfo'

require './lib/calendar/GoogleCalendar'

class PanelsController < ApplicationController
  before_filter AuthFilter

  @@tz = TZInfo::Timezone.get('America/Los_Angeles').current_period

  class NewHelper
    def initialize(session, start_time, end_time, pool_id = 0)
      @session = session
      @start_time = start_time
      @end_time = end_time
      @pool_id = pool_id
    end
    
    attr_accessor :session, :start_time, :end_time, :panel_name, :pool_id
  end
    
  # GET /panels
  # GET /panels.json
  def index
    @panels = Panel.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @panels }
    end
  end

  # GET /panels/1
  # GET /panels/1.json
  def show
    @panel = Panel.find(params[:id])
    @tz = @@tz
    
    cal = GoogleCalendar.new(AuthController.gclient)
    scheduler = InterviewerScheduler.new(cal)
    @panel.sessions.each {|s| scheduler.update_status(s)}
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @panel }
    end
  end

  #helper :all
  # GET /panels/new
  # GET /panels/new.json
  def new
    @panel = Panel.new
    
    starts = [10, 11, 13, 14, 15]
    @sessions = []
    for st in starts      
      s = @panel.sessions.new(:panel => @panel,
                              :state => Session::UNSCHEDULED)
      @sessions << NewHelper.new(s, st, st + 1)
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @panel }
    end
  end

  # GET /panels/1/edit
  def edit
    @panel = Panel.find(params[:id])
  end
  
  # POST /panels
  # POST /panels.json
  def create
    @panel = Panel.new(params[:panel])

    @sessions = []
    sessions = []
    sessionsParams = params[:session]
    (0...sessionsParams.size).each do |i|
      sessionParams = sessionsParams[i.to_s]
      pool = InterviewerPool.find(sessionParams[:pool_id])
      
      tz_s = @@tz.abbreviation.to_s
      sstart = DateTime.new(@panel.date.year, @panel.date.mon, @panel.date.mday, sessionParams[:start].to_i, 0, 0, tz_s)
      send = DateTime.new(@panel.date.year, @panel.date.mon, @panel.date.mday, sessionParams[:end].to_i, 0, 0, tz_s)
      s = @panel.sessions.new(:panel => @panel,
                              :interviewer_pool => pool,
                              :start => sstart,
                              :end => send,
                              :state => Session::UNSCHEDULED)
      @sessions << NewHelper.new(s, sstart.hour, send.hour, pool.id)
    end
    
    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          @panel.sessions.each do |s|
            cal = GoogleCalendar.new(AuthController.gclient)
            InterviewerScheduler.new(cal).schedule(s)
          end
          
          @panel.save!
        end
      end
    
      if @panel.save
        format.html { redirect_to @panel, :notice => 'Panel was successfully created.' }
        format.json { render :json => @panel, :status => :created, :location => @panel }
      else
        format.html { render :action => "new" }
        format.json { render :json => @panel.errors, :status => :unprocessable_entity }
      end
    end
  end

# update/destroy not yet supported
=begin
  # PUT /panels/1
  # PUT /panels/1.json
  def update
    @panel = Panel.find(params[:id])

    respond_to do |format|
      if @panel.update_attributes(params[:panel])
        format.html { redirect_to @panel, :notice => 'Panel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @panel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /panels/1
  # DELETE /panels/1.json
  def destroy
    @panel = Panel.find(params[:id])
    @panel.destroy

    respond_to do |format|
      format.html { redirect_to panels_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/panels_helper.rb
module PanelsHelper
  def sessionTimeLabel(from, to)
    from.to_s + ":00 to " + to.to_s + ":00"
  end
  
  def poolNames
    InterviewerPool.all.map {|p| [p.name, p.id]}
  end
  
  def panel_state(panel)
    states = panel.sessions.map { |s| s.state }
    if(states.index {|s| s != Session::CONFIRMED}.nil?)
      "ok"
    elsif(!states.index(Session::FAILED).nil?)
      "error - some sessions could not be scheduled"
    else
      "pending - has unconfirmed sessions"
    end
  end
  
  def interviewer_name(interviewer)
    interviewer.nil? ? 'none' : interviewer.name
  end
end

app/views/panels/_form.html.erb
<%= form_for(@panel) do |f| %>
  <% if @panel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panel.errors.count, "error") %> prohibited this panel from being saved:</h2>

      <ul>
      <% @panel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candidate %><br />
    <%= f.text_field :candidate %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  
  <% index = 0 %>
  <% @sessions.each do |sh| %>
      <div class="field">
        <%= label :session, sessionTimeLabel(sh.start_time, sh.end_time) %><br/>
        <%= select :session, "#{index}[pool_id]", poolNames, :selected => sh.pool_id %>
        <%= hidden_field :session, "#{index}[start]", :value => sh.start_time %>
        <%= hidden_field :session, "#{index}[end]", :value => sh.end_time %>
      </div>
      <% index += 1 %>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/panels/edit.html.erb
<h1>Editing panel</h1>

<%= render 'form' %>

<%= link_to 'Show', @panel %> |
<%= link_to 'Back', panels_path %>

app/views/panels/index.html.erb
<h1>Interview Panels</h1>

<p>
Interview panels coordinate a schedule of sessions through which potential candidates go through.
</p>

<table>
  <tr>
    <th>Candidate</th>
    <th>Email</th>
    <th>Position</th>
    <th>Date</th>
    <th>State</th>
    <th></th>
    <!-- <th></th>
    <th></th> -->
  </tr>

<% @panels.each do |panel| %>
  <tr>
    <td><%= panel.candidate %></td>
    <td><%= panel.email %></td>
    <td><%= panel.position %></td>
    <td><%= panel.date %></td>
    <td><%= panel_state(panel) %></td>
    <td><%= link_to 'Show', panel %></td>
    <!-- <td><%= link_to 'Edit', edit_panel_path(panel) %></td>
    <td><%= link_to 'Destroy', panel, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Panel', new_panel_path %>

app/views/panels/new.html.erb
<h1>New panel</h1>

<%= render 'form' %>

<%= link_to 'Back', panels_path %>

app/views/panels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Candidate:</b>
  <%= @panel.candidate %>
</p>

<p>
  <b>Email:</b>
  <%= @panel.email %>
</p>

<p>
  <b>Position:</b>
  <%= @panel.position %>
</p>

<p>
  <b>Date:</b>
  <%= @panel.date %>
</p>

<p>
  <b>State:</b>
  <%= panel_state(@panel) %>
</p>

<% @panel.sessions.each do |s| %>
  <p>
    <%= @tz.to_local(s.start.to_datetime) %> - <%= @tz.to_local(s.end.to_datetime) %> :
    <%= interviewer_name(s.interviewer) %>
    (<%= Session.stateName(s.state) %>)
  </p>
<% end %>

<!-- <%= link_to 'Edit', edit_panel_path(@panel) %> | -->
<%= link_to 'Back', panels_path %>