config/routes.rb
Interviews::Application.routes.draw do
  root :to => "home#index"
  
  resources :panels
  resources :interviewer_pools
  resources :interviewers
  resources :auth

  get "home/index"

end

app/models/interviewer.rb
require 'valid_email'

class Interviewer < ActiveRecord::Base
  validates :name,  :presence => true
  validates :email, :presence => true, :email => true, :uniqueness => true
  
  has_many :interviewer_pool_memberships, :dependent => :destroy
  has_many :interviewer_pools, :through => :interviewer_pool_memberships
end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
  # GET /interviewers
  # GET /interviewers.json
  def index
    @interviewers = Interviewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @interviewers }
    end
  end

  # GET /interviewers/1
  # GET /interviewers/1.json
  def show
    @interviewer = Interviewer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @interviewer }
    end
  end

  # GET /interviewers/new
  # GET /interviewers/new.json
  def new
    @interviewer = Interviewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @interviewer }
    end
  end

  # GET /interviewers/1/edit
  def edit
    @interviewer = Interviewer.find(params[:id])
  end

  # POST /interviewers
  # POST /interviewers.json
  def create
    @interviewer = Interviewer.new(params[:interviewer])

    respond_to do |format|
      if @interviewer.save
        format.html { redirect_to @interviewer, :notice => 'Interviewer was successfully created.' }
        format.json { render :json => @interviewer, :status => :created, :location => @interviewer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @interviewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interviewers/1
  # PUT /interviewers/1.json
  def update
    @interviewer = Interviewer.find(params[:id])

    respond_to do |format|
      if @interviewer.update_attributes(params[:interviewer])
        format.html { redirect_to @interviewer, :notice => 'Interviewer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @interviewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewers/1
  # DELETE /interviewers/1.json
  def destroy
    @interviewer = Interviewer.find(params[:id])
    @interviewer.destroy

    respond_to do |format|
      format.html { redirect_to interviewers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interviewers_helper.rb
module InterviewersHelper
end

app/views/interviewers/_form.html.erb
<%= form_for(@interviewer) do |f| %>
  <% if @interviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interviewer.errors.count, "error") %> prohibited this interviewer from being saved:</h2>

      <ul>
      <% @interviewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviewers/edit.html.erb
<h1>Editing interviewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @interviewer %> |
<%= link_to 'Back', interviewers_path %>

app/views/interviewers/index.html.erb
<h1>Interviewers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviewers.each do |interviewer| %>
  <tr>
    <td><%= interviewer.name %></td>
    <td><%= interviewer.email %></td>
    <td><%= link_to 'Show', interviewer %></td>
    <td><%= link_to 'Edit', edit_interviewer_path(interviewer) %></td>
    <td><%= link_to 'Destroy', interviewer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interviewer', new_interviewer_path %>

app/views/interviewers/new.html.erb
<h1>New interviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', interviewers_path %>