config/routes.rb
Interviews::Application.routes.draw do
  root :to => "home#index"
  
  resources :panels
  resources :interviewer_pools
  resources :interviewers
  resources :auth

  get "home/index"

end

app/models/interviewer_pool.rb
class InterviewerPool < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  has_many :interviewer_pool_memberships, :dependent => :destroy
  has_many :interviewers, :through => :interviewer_pool_memberships
  
  #has_and_belongs_to_many :interviewers
  accepts_nested_attributes_for :interviewers
end

app/controllers/interviewer_pools_controller.rb
class InterviewerPoolsController < ApplicationController
  # GET /interviewer_pools
  # GET /interviewer_pools.json
  def index
    @interviewer_pools = InterviewerPool.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @interviewer_pools }
    end
  end

  # GET /interviewer_pools/1
  # GET /interviewer_pools/1.json
  def show
    @interviewer_pool = InterviewerPool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @interviewer_pool }
    end
  end

  # GET /interviewer_pools/new
  # GET /interviewer_pools/new.json
  def new
    @interviewer_pool = InterviewerPool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @interviewer_pool }
    end
  end

  # GET /interviewer_pools/1/edit
  def edit
    @interviewer_pool = InterviewerPool.find(params[:id])
  end

  # POST /interviewer_pools
  # POST /interviewer_pools.json
  def create
    @interviewer_pool = InterviewerPool.new(params[:interviewer_pool])

    respond_to do |format|
      if @interviewer_pool.save
        format.html { redirect_to @interviewer_pool, :notice => 'Interviewer pool was successfully created.' }
        format.json { render :json => @interviewer_pool, :status => :created, :location => @interviewer_pool }
      else
        format.html { render :action => "new" }
        format.json { render :json => @interviewer_pool.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interviewer_pools/1
  # PUT /interviewer_pools/1.json
  def update
    @interviewer_pool = InterviewerPool.find(params[:id])

    respond_to do |format|
      if @interviewer_pool.update_attributes(params[:interviewer_pool])
        format.html { redirect_to @interviewer_pool, :notice => 'Interviewer pool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @interviewer_pool.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewer_pools/1
  # DELETE /interviewer_pools/1.json
  def destroy
    @interviewer_pool = InterviewerPool.find(params[:id])
    @interviewer_pool.destroy

    respond_to do |format|
      format.html { redirect_to interviewer_pools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interviewer_pools_helper.rb
module InterviewerPoolsHelper
  def has_interviewer(pool, interviewer)
    pool.interviewers.include?(interviewer)
  end
end

app/views/interviewer_pools/_form.html.erb
<%= form_for(@interviewer_pool) do |f| %>
  <% if @interviewer_pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interviewer_pool.errors.count, "error") %> prohibited this interviewer_pool from being saved:</h2>

      <ul>
      <% @interviewer_pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <ul class="checkbox-list">
  <% Interviewer.all.each do |interviewer| %>
    <li><%= check_box_tag "interviewer_pool[interviewer_ids][]", interviewer.id, has_interviewer(@interviewer_pool, interviewer) %> <%= interviewer.name %></li>
    <% end %>
  </ul>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviewer_pools/edit.html.erb
<h1>Editing interviewer_pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @interviewer_pool %> |
<%= link_to 'Back', interviewer_pools_path %>

app/views/interviewer_pools/index.html.erb
<h1>Interviewer Pools</h1>

<p>
Interview pools group interviewers by topics or specialities. 
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Interviewers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviewer_pools.each do |interviewer_pool| %>
  <tr>
    <td><%= interviewer_pool.name %></td>
    <td><%= interviewer_pool.interviewers.map { |i| i.name }.join(", ") %></td>
    <td><%= link_to 'Show', interviewer_pool %></td>
    <td><%= link_to 'Edit', edit_interviewer_pool_path(interviewer_pool) %></td>
    <td><%= link_to 'Destroy', interviewer_pool, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interviewer pool', new_interviewer_pool_path %>

app/views/interviewer_pools/new.html.erb
<h1>New interviewer_pool</h1>

<%= render 'form' %>

<%= link_to 'Back', interviewer_pools_path %>

app/views/interviewer_pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @interviewer_pool.name %>
</p>

<p>
  <b>Interviewers:</b>
  <%= @interviewer_pool.interviewers.map { |i| i.name }.join(", ") %>
</p>


<%= link_to 'Edit', edit_interviewer_pool_path(@interviewer_pool) %> |
<%= link_to 'Back', interviewer_pools_path %>